services:
  app:
    image: mysociety/climate_action_plans_dataset:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspaces/climate_action_plans_dataset
    volumes:
      - ./:/workspaces/climate_action_plans_dataset/
